// Generated by CoffeeScript 1.4.0
(function() {
  var $sets, Operate, jugglerParams, mongojs;

  mongojs = require("mongojs");

  $sets = {};

  Operate = function(params, req, res) {
    var operation, operator;
    operator = Operate.get(params.operator);
    if (operator) {
      operation = operator.operation(params.operation);
      if (operation) {
        return operation(params, function(response) {
          return res.send(response);
        });
      } else {
        return res.send("NooooOp");
      }
    } else {
      return res.send("NoOp");
    }
  };

  Operate.set = function(anAlias, anOperate) {
    return $sets[anAlias] = anOperate;
  };

  Operate.get = function(anAlias) {
    return $sets[anAlias];
  };

  Operate.byRESTSyntax = function(req, res) {
    var m;
    m = {
      "message": "NO_REST_SYNTAX",
      "collection": req.params[0],
      "id": req.params[1]
    };
    return res.send(m);
  };

  jugglerParams = function(req) {
    var operator, params, rName, resources, rid;
    rName = req.params[2];
    resources = rName.split("_");
    operator = "_default_";
    if (req.params[0] != null) {
      operator = req.params[0];
    }
    rid = null;
    if (resources[1] != null) {
      rid = resources[1];
    }
    params = {
      'operator': operator,
      'operation': req.params[1],
      'rName': rName,
      'rKind': resources[0],
      'rId': rid,
      'query': req.query,
      'body': req.body
    };
    console.log(params);
    return params;
  };

  Operate.byJugglerSyntax = function(req, res) {
    var allowed, params;
    params = jugglerParams(req);
    allowed = {
      GET: ['Query', 'Get'],
      POST: ['Edit', 'Delete', 'Create']
    };
    return Operate(params, req, res);
  };

  module.exports = Operate;

}).call(this);
