// Generated by CoffeeScript 1.4.0
(function() {
  var actions, mainServer;

  actions = {};

  actions.Server = function(params, callback) {
    return callback("SerADFSADSFver");
  };

  actions.Version = actions.Server;

  mainServer = {};

  mainServer.action = function(anAction) {
    return actions[anAction];
  };

  module.exports = mainServer;

}).call(this);
