// Generated by CoffeeScript 1.4.0
(function() {
  var Operate;

  Operate = require('../../lib/middleware/Operate');

  Operate.set('_default_', require('../../lib/operators/crud'));

  module.exports = Operate;

}).call(this);
