// Generated by CoffeeScript 1.4.0
(function() {
  var Operator, PORT, ServerDispatcher, app, express;

  express = require("express");

  Operator = require("./app/middleware/Operate");

  ServerDispatcher = require("./app/middleware/ServerDispatcher");

  PORT = 3000;

  app = express();

  app.set('cfg', require("./app/config"));

  app.set('env', app.get('cfg').env);

  app.use(express["static"](__dirname + '/public'));

  app.use(express.bodyParser());

  app.configure('development', function() {
    return app.get('/SchemaReset/', require("./app/controller/SchemaReset"));
  });

  app.get(/^\/--([A-Z][a-z]+)?([A-Z][a-z]+):([\w_]+)?$/, Operator.byJugglerSyntax);

  app.post(/^\/--([A-Z][a-z]+)?([A-Z][a-z]+):([\w_]+)?$/, Operator.byJugglerSyntax);

  app.get(/^\/\$(\w+:)?(\w+)/, ServerDispatcher);

  app.post(/^\/\$(\w+:)?(\w+)/, ServerDispatcher);

  app.post(/post/, function(req, res) {
    return res.send(req.body);
  });

  app.listen(PORT);

}).call(this);
