// Generated by CoffeeScript 1.4.0
(function() {
  var SchemaReset, collections, mongojs;

  mongojs = require("mongojs");

  collections = {
    'Communities': require("../data/communities"),
    'Courses': require("../data/courses"),
    'Projects': require("../data/projects"),
    'Subjects': require("../data/subjects")
  };

  SchemaReset = function(req, res) {
    var coll, collection, db, name, registro, _i, _len;
    db = mongojs('guti');
    for (name in collections) {
      coll = collections[name];
      collection = db.collection(name);
      collection.remove({});
      for (_i = 0, _len = coll.length; _i < _len; _i++) {
        registro = coll[_i];
        console.log(registro);
        collection.save(registro, function() {
          return console.log("9");
        });
      }
    }
    return res.send("SchemaReset");
  };

  module.exports = SchemaReset;

}).call(this);
